config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: ""

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :events
  resources :users, only: [ :show ]
  resources :event_attendings, only: [ :create, :destroy ]
  resources :event_invites, except: [ :edit, :update ]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendings, foreign_key: "attended_event_id"
  has_many :attendees, through: :event_attendings
  has_many :event_invites, foreign_key: "invite_event_id"

  default_scope {order :time}

  current_time = Time.now.strftime "%Y-%m-%dT%T" # using default time format of datatime_field
  scope :past, -> { where "time < ?", [ current_time ] }
  scope :upcoming, -> { where "time > ?", [ current_time ] }

  enum :visibility, { public: 0, private: 1 }, suffix: true
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"

  validates :attendee_id, uniqueness: { message: "already joined this event", scope: [ :attended_event_id ] }
end

app/models/event_invite.rb
class EventInvite < ApplicationRecord
  belongs_to :invite_event, class_name: "Event"
  belongs_to :invited_user, class_name: "User"

  validates :invited_user_id, uniqueness: { message: "is already in invite list", scope: [ :invite_event_id ] }

  enum :status, { pending: 0, accepted: 1, rejected: 2 }, suffix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :event_attendings, foreign_key: "attendee_id"
  has_many :attended_events, through: :event_attendings
  has_many :event_invites, foreign_key: "invited_user_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :authenticate_user!
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def create
    @event_attending = EventAttending.build attendee_id: params[:user_id], attended_event_id: params[:event_id]

    if @event_attending.save
      redirect_back fallback_location: root_path, notice: "You joined the event!"
    end
  end

  def destroy
    @event_attending = EventAttending.find [ params[:user_id], params[:event_id] ]
    @event_attending.destroy
    redirect_back fallback_location: root_path, notice: "You left the event."
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build event_params

    if @event.save
      redirect_to user_path current_user.id
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find params[:id]
    is_creator = @event.creator_id == current_user.id
    is_invited = @event.event_invites.any? { |invite| invite.invited_user_id == current_user.id }
    is_attending = @event.attendee_ids.any?(current_user.id)

    unless @event.public_visibility? || is_creator || is_invited || is_attending
      redirect_back fallback_location: root_path, status: 403, notice: "This event is private."
    end
  end

  def edit
    @event = Event.find params[:id]

    if @event.creator_id != current_user.id
      redirect_back fallback_location: root_path, notice: "You can't edit this event."
      return
    end
  end

  def update
    @event = Event.find params[:id]

    return render :edit, status: :forbidden unless @event.creator_id == current_user.id

    if @event.update(event_params)
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find params[:id]

    if @event.creator_id != current_user.id
      redirect_back fallback_location: root_path, status: :forbidden, notice: "You can't delete this event."
      return
    end

    @event.destroy
    redirect_back fallback_location: root_path, notice: "You deleted an event."
  end

  private

  def event_params
    p = params.expect event: [ :name, :time, :location, :visibility ]
    p[:visibility] = p[:visibility].to_i
    p
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event do |event| %>
  <div>
    <%= event.label :name %>
    <%= event.text_field :name %>
  </div>

  <div>
    <%= event.label :time %>
    <%= event.datetime_field :time %>
  </div>

  <div>
    <%= event.label :location %>
    <%= event.text_field :location %>
  </div>

  <div>
    <%= event.checkbox :visibility, checked: true %>
    <%= event.label :visibility, "Private" %>
  </div>

  <div>
    <%= event.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h1>Public events</h1>
<% events = @events.public_visibility %>

<h2>Upcoming</h2>
<%= render(partial: "shared/event_cards", collection: events.upcoming, as: :event) ||
  render(inline: "<p>There are no upcoming events yet.</p>") %>

<h2>Past</h2>
<%= render(partial: "shared/event_cards", collection: events.past, as: :event) ||
  render(inline: "<p>There are no past events yet.</p>") %>

app/views/events/new.html.erb
<h1>Create new event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p>Time: <%= @event.time.sub("T", ", ") %></p>
<p>Location: <%= @event.location %></p>
<p>Attendees:</p>
<ul>
<% @event.attendees.each do |attendee|%>
  <li><%= attendee.email %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Public events", events_path %>
      <%= link_to "My events", user_path(current_user.id) unless current_user.nil?%>
      <%= link_to "New event", new_event_path %>

      <% if signed_in? %>
        <%= link_to "Sign out", sign_out_path %>
      <% else %>
        <%= link_to "Sign in", sign_in_path %>
      <% end %>
    </nav>

    <% flash.each do |name, message| %>
      <p class="<%= name %>"><%= message %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_event_cards.html.erb
<hr>
<h3><%= link_to event.name, event_path(event.id) %></h3>
<p>Host: <%= User.find(event.creator_id).email %></p>
<p>Location: <%= event.location %></p>
<p>Time: <%= event.time.sub("T", ", ") %></p>
<p>Type: <%= event.public_visibility? ? "public" : "private" %></p>
<div class="card-buttons" style="display: flex; gap: 5px">
<% if event.attendee_ids.none?(current_user.id) %>
  <%= button_to "Join", event_attendings_path, params: { user_id: current_user.id, event_id: event.id } %>
<% else %>
  <!-- for some unknown to me reason, you need to pass id to delete method. Even if you don't have such column in the table. And yes, -->
  <!-- I did try to pass [current_user.id, event.id] as an id, it did not work. I'm really mad for losing hours of my sleep just to -->
  <!-- search for "proper" solution, at this point I just give up. -->
  <%= button_to "Leave", event_attending_path(user_id: current_user.id, event_id: event.id, id: 0), method: :delete %>
<% end %>

<% if event.creator_id == current_user.id %>
  <%= button_to "Delete", event_path(id: event.id), method: :delete %>
  <%= link_to "Edit", edit_event_path(id: event.id) %>
<% end %>
</div>

app/views/users/show.html.erb
<h2>Events created by <%= @user.email %></h2>
<% created_events = @user.id == current_user.id ? @user.created_events : @user.created_events.public_visibility %>
<% attended_events = @user.id == current_user.id ? @user.attended_events : @user.attended_events.public_visibility %>

<h3>Upcoming</h3>
<%= render(partial: "shared/event_cards", collection: created_events.upcoming, as: :event) ||
  render(inline: "<p>User has no created events.</p>")%>

<h3>Passed</h3>
<%= render(partial: "shared/event_cards", collection: created_events.past, as: :event) ||
  render(inline: "<p>User has no created events.</p>")%>

<h2>Events attended by <%= @user.email %></h2>

<h3>Upcoming</h3>
<%= render(partial: "shared/event_cards", collection: attended_events.upcoming, as: :event) ||
  render(inline: "<p>You aren't attending any events.</p>") %>

<h3>Passed</h3>
<%= render(partial: "shared/event_cards", collection: attended_events.past, as: :event) ||
  render(inline: "<p>You aren't attending any events.</p>") %>